Repository 9weeks-app-web/Team-8, pull requests merged in 2024-01, with the labels that each got.

#12 ✨[Feat] 라우터 및 초기 세팅 #8
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/pull_request_template.md
  8-bit/src/components/AuthInput.tsx
  8-bit/src/layout/NoFooterLayout.tsx
  8-bit/src/pages/community/CommunityBoard.tsx
  8-bit/src/pages/community/CommunityHome.tsx
  8-bit/src/pages/community/CommunityHot.tsx
  8-bit/src/pages/community/communityQna.tsx
  8-bit/src/routes.tsx
Labels: feature, approved

#14 💄[Design]공통 스타일 설정 (1차) #9
  8-bit/package-lock.json
  8-bit/src/routes.tsx
  8-bit/src/styles/common.ts
Labels: feature, style, on hold

#16 ✨[Feat] 홈페이지 메인 배너 마크업, 스타일링 #15
  8-bit/package-lock.json
  8-bit/package.json
  8-bit/src/components/HomeBanner.tsx
  8-bit/src/pages/Home.tsx
Labels: feature, style, in review

#18 ✨[Feat] 로그인 기능 구현 #6
  8-bit/public/applesns.svg
  8-bit/public/googlesns.svg
  8-bit/public/kakaosns.svg
  8-bit/public/loginfooterimg.svg
  8-bit/public/logo.svg
  8-bit/public/naversns.svg
  8-bit/src/firebase.tsx
  8-bit/src/pages/SignIn.tsx
  8-bit/src/pages/SignUp.tsx
Labels: feature

#19 ✨[Feat] Header, Footer 구현 #10
  8-bit/public/facebook.svg
  8-bit/public/familysite.svg
  8-bit/public/instagram.svg
  8-bit/public/sfac_logo.svg
  8-bit/public/sniperfactory.svg
  8-bit/public/youtube.svg
  8-bit/src/layout/Footer.tsx
  8-bit/src/layout/Header.tsx
  8-bit/src/routes.tsx
Labels: feature

#22 ✨[Feat] 홈페이지 메인 배너 검색창 클릭시 모달 보이게끔 기능 구현 #15
  8-bit/src/components/HomeBanner.tsx
  8-bit/src/components/HomeServices.tsx
  8-bit/src/pages/Home.tsx
  8-bit/src/styles/common.ts
Labels: enhancement, feature, style

#24 ✨ [Feature] 메인페이지 세미폴리오 컴포넌트 구현 #13
  8-bit/public/home/Frame 1000005921.png
  8-bit/src/components/Portfolio.tsx
  8-bit/src/components/PortfolioFilter.tsx
  8-bit/src/components/SemifoiloInfo.tsx
  8-bit/src/components/SemifoiloModal.tsx
  8-bit/src/components/Semifolio.tsx
  8-bit/src/db/SemifolioDatas.tsx
  8-bit/src/pages/Home.tsx
Labels: feature, style, merge conflict

#28 ✨[Feat] 홈페이지 추가 서비스 섹션 마크업, 스타일링 작업중 #17
  8-bit/src/components/HomeBanner.tsx
Labels: feature, style

#29 💄[Design] 홈페이지 추가 서비스 부분 스타일링 #17
  8-bit/public/home/GetQuote.svg
  8-bit/public/home/card1.png
  8-bit/public/home/card2.png
  8-bit/src/components/HomeServices.tsx
  8-bit/src/styles/common.ts
Labels: style

#35 💄[Design] 홈페이지 추가 서비스 섹션, 인기멘토 부분 스타일링 #17
  8-bit/src/components/HomeServices.tsx
Labels: style

#36 ✨ [Feat] SemifolioInfo 컴포넌트 사이 HomeServices 컴포넌트 배치 #34
  8-bit/src/components/HomePortfolio.tsx
  8-bit/src/components/HomeSemifolio.tsx
  8-bit/src/components/HomeServices.tsx
  8-bit/src/components/SemifoiloInfo.tsx
Labels: feature

#37 💄[Design] 홈페이지 추가 서비스 섹션 마크업, 스타일링 #17
  8-bit/public/home/Group1171277623.svg
  8-bit/public/home/bookmark.svg
  8-bit/public/home/gsRetail.png
  8-bit/public/home/sideprojecticon.svg
  8-bit/public/home/sideprojecticon2.svg
  8-bit/src/components/HomeServices.tsx
  8-bit/src/pages/Home.tsx
Labels: feature, style

#39 ✨[Feat]로그인,회원가입 전체 디자인 기능구현 #26
  8-bit/public/applesns.svg
  8-bit/public/auth/applesns.svg
  8-bit/public/auth/googlesns.svg
  8-bit/public/auth/kakaosns.svg
  8-bit/public/auth/loginfooterimg.svg
  8-bit/public/auth/logo.svg
  8-bit/public/auth/naversns.svg
  8-bit/public/auth/signupsuccessicon.png
  8-bit/public/googlesns.svg
  8-bit/public/kakaosns.svg
  8-bit/public/naversns.svg
  8-bit/src/pages/auth/FindId.tsx
  8-bit/src/pages/auth/FindPassword.tsx
  8-bit/src/pages/auth/SignIn.tsx
  8-bit/src/pages/auth/SignUp.tsx
  8-bit/src/pages/auth/SignupSuccess.tsx
  8-bit/src/pages/auth/SignupTwo.tsx
  8-bit/src/routes.tsx
Labels: feature

#41 ✨[Feat] 메시지, 알림 모달 구현 #21
  8-bit/public/noti_message.svg
  8-bit/src/components/HeaderModal.tsx
  8-bit/src/components/MeassageModal.tsx
  8-bit/src/components/NotiModal.tsx
  8-bit/src/layout/Header.tsx
Labels: feature

#42 ✨[Feat] 로그인 시 헤더 변경 구현 #32
  8-bit/public/footer/facebook.svg
  8-bit/public/footer/familysite.svg
  8-bit/public/footer/instagram.svg
  8-bit/public/footer/sniperfactory.svg
  8-bit/public/footer/youtube.svg
  8-bit/public/header/noti_message.svg
  8-bit/public/header/sfac_logo.svg
  8-bit/src/components/NotiModal.tsx
  8-bit/src/layout/Footer.tsx
  8-bit/src/layout/Header.tsx
Labels: feature

#47 💄[Disign] 회원가입 디자인, 기능 수정 작업 #46
  8-bit/public/home/Frame 1000005921.png
  8-bit/src/components/AuthInput.tsx
  8-bit/src/components/SemifoiloInfo.tsx
  8-bit/src/db/SemifolioDatas.tsx
  8-bit/src/pages/UploadPage.tsx
  8-bit/src/pages/auth/Profile.tsx
  8-bit/src/pages/auth/SignIn.tsx
  8-bit/src/pages/auth/SignUp.tsx
  8-bit/src/routes.tsx
Labels: feature, style

#50 ✨[Feat] 마이페이지 마크업, 스타일링 작업#38
  8-bit/public/facebook.svg
  8-bit/public/github.svg
  8-bit/public/instagram.png
  8-bit/public/naver.png
  8-bit/src/components/HomeBanner.tsx
  8-bit/src/components/HomeServices.tsx
  8-bit/src/components/SemifoiloInfo.tsx
  8-bit/src/components/mypage/MainContent.tsx
  8-bit/src/components/mypage/ProfileSidebarComponent.tsx
  8-bit/src/components/mypage/SkillBar.tsx
  8-bit/src/pages/MyPage.tsx
  8-bit/src/pages/mypage/MyPage.tsx
  8-bit/src/routes.tsx
Labels: feature, style

#49 [Feat] 세미폴리오 디자인 및 필터 기능 추가 #48
  8-bit/package-lock.json
  8-bit/package.json
  8-bit/public/home/Union.png
  8-bit/public/home/modalImg.png
  8-bit/public/home/pick_noShadow.svg
  8-bit/src/App.tsx
  8-bit/src/components/HomePortfolio.tsx
  8-bit/src/components/HomePortfolioFilter.tsx
  8-bit/src/components/HomeSemifoiloInfo.tsx
  8-bit/src/components/HomeSemifolio.tsx
  8-bit/src/components/HomeServices.tsx
  8-bit/src/components/SemifoiloModal.tsx
  8-bit/src/db/SemifolioDatas.tsx
  8-bit/src/pages/Home.tsx
  8-bit/src/recoil/SemifoiloAtum.tsx
Labels: feature, style

#52 [Design] 업로드 페이지 1차 디자인 구현#40
  8-bit/public/upload/embed.png
  8-bit/public/upload/embedUpload.png
  8-bit/public/upload/imageUpload.png
  8-bit/public/upload/photo.png
  8-bit/public/upload/text.png
  8-bit/public/upload/textUpload.png
  8-bit/public/upload/video.png
  8-bit/public/upload/videoUpload.png
  8-bit/src/components/ColorModal.tsx
  8-bit/src/pages/UploadPage.tsx
  8-bit/src/pages/auth/Profile.tsx
  8-bit/src/pages/auth/SignIn.tsx
  8-bit/src/pages/auth/SignUp.tsx
Labels: style

#53 💄[Design] Footer 디자인 변경 #44
  8-bit/src/layout/Footer.tsx
Labels: style

#54 ✨ [Feat] 정렬, 스타일 드롭다운 디자인 및 기능 #48
  8-bit/public/home/Union.png
  8-bit/public/home/bookmarksIcon.svg
  8-bit/public/home/forumIcon.svg
  8-bit/public/home/likesIcon.svg
  8-bit/public/home/shareIcon.svg
  8-bit/src/components/HomePortfolio.tsx
  8-bit/src/components/HomePortfolioFilter.tsx
  8-bit/src/components/HomeSemifoiloInfo.tsx
  8-bit/src/components/HomeSemifolio.tsx
  8-bit/src/components/SemifoiloModal.tsx
  8-bit/src/recoil/SemifoiloAtum.tsx
Labels: feature, style

#57 [Design] 업로드 디자인 구현 완료 #56
  8-bit/package-lock.json
  8-bit/package.json
  8-bit/src/components/upload/ColorModal.tsx
  8-bit/src/components/upload/NextUploadModal.tsx
  8-bit/src/pages/auth/SignIn.tsx
  8-bit/src/pages/upload/UploadPage.tsx
  8-bit/src/pages/upload/UploadSuccess.tsx
  8-bit/src/routes.tsx
Labels: style

#58 ✨[Feature] 프로필, 업로드 모달 창 구현 #45
  8-bit/public/footer/facebook.png
  8-bit/public/footer/facebook.svg
  8-bit/public/footer/instagram.png
  8-bit/public/footer/instagram.svg
  8-bit/public/footer/youtube.png
  8-bit/public/footer/youtube.svg
  8-bit/public/header/portfolio.svg
  8-bit/public/header/semifolio.svg
  8-bit/public/user_profile.png
  8-bit/src/components/HeaderModal.tsx
  8-bit/src/components/MeassageModal.tsx
  8-bit/src/components/NotiModal.tsx
  8-bit/src/components/ProfileModal.tsx
  8-bit/src/components/UploadModal.tsx
  8-bit/src/layout/Header.tsx
Labels: enhancement, feature

#60 [Feat] 업로드 이미지 추가 기능 구현 #59
  8-bit/src/pages/upload/UploadPage.tsx
Labels: feature

#63 ✨ [Feat] 세미폴리오 모달창 수정 #55
  8-bit/public/home/bigBookmarksIcon.svg
  8-bit/public/home/bigLikesIcon.svg
  8-bit/public/home/commentImg.svg
  8-bit/public/home/eyesIconGray.svg
  8-bit/public/home/eyesIconWhite.svg
  8-bit/public/home/likesIconGray.svg
  8-bit/public/home/modalGreenDot.svg
  8-bit/public/home/modalImg.png
  8-bit/public/home/pick.svg
  8-bit/public/home/pick_noShadow.svg
  8-bit/public/home/semifolio/1.png
  8-bit/public/home/semifolio/10.jpg
  8-bit/public/home/semifolio/11.jpg
  8-bit/public/home/semifolio/12.png
  8-bit/public/home/semifolio/13.png
  8-bit/public/home/semifolio/14.png
  8-bit/public/home/semifolio/15.png
  8-bit/public/home/semifolio/16.jpg
  8-bit/public/home/semifolio/17.jpg
  8-bit/public/home/semifolio/18.jpg
  8-bit/public/home/semifolio/19.jpg
  8-bit/public/home/semifolio/2.jpg
  8-bit/public/home/semifolio/20.jpg
  8-bit/public/home/semifolio/3.jpg
  8-bit/public/home/semifolio/4.jpg
  8-bit/public/home/semifolio/5.png
  8-bit/public/home/semifolio/6.jpg
  8-bit/public/home/semifolio/7.jpg
  8-bit/public/home/semifolio/8.png
  8-bit/public/home/semifolio/9.jpg
  8-bit/public/home/semifolio/modal1.png
  8-bit/public/home/semifolio/modal2.png
  8-bit/public/home/semifolio/modal3.png
  8-bit/public/home/semifolio/modal4.png
  8-bit/public/home/semifolio/modalHover1.svg
  8-bit/public/home/semifolio/modalHover2.svg
  8-bit/public/home/semifolio/modalHover3.svg
  8-bit/public/home/semifolio/userImg1.png
  8-bit/public/home/viewsIcon.svg
  8-bit/src/components/HomePortfolioFilter.tsx
  8-bit/src/components/HomeSemifoiloInfo.tsx
  8-bit/src/components/SemifoiloModal.tsx
  8-bit/src/db/SemifolioDatas.tsx
Labels: feature, style

#69 🐛[Fix] 라우트 오타 수정 #68
  8-bit/src/components/MeassageModal.tsx
  8-bit/src/components/NotiModal.tsx
  8-bit/src/db/chatDatas.tsx
  8-bit/src/pages/Chat.tsx
  8-bit/src/routes.tsx
Labels: bug
